
analyzer:
  exclude:
    - build/**.dart
    - lib/**/*.g.dart
    - _resources/**.dart
    - lib/api/pb/dart/**.dart
    - lib/model/*.g.dart
    - lib/generated/**.dart
    - platform_source/**.dart

include: package:lints/recommended.yaml

linter:
  rules:
    - use_super_parameters
